### ISSUE TITLE
2 players: sides, turns

### ISSUE THREAD

**Issue by ssk97** [RonWeber/DataStrategyGame#10]
We need to identify units as being on a side and support the two players having their own turns.

**Comment by RonWeber** [comment]
Done.

**Comment by ssk97** [comment]
Would it be possible to make something to have the the same units on different sides? The differences would be "side", "image", and "id", probably put in an array or something.

Not necessary but would be helpful.

**Comment by RonWeber** [comment]
Didn't we agree that we aren't doing that?

**Comment by ssk97** [comment]
In the JSON. They'd be 2 separate units in the end.

**Comment by RonWeber** [comment]
Didn't we agree that we aren't doing that?

**Comment by RonWeber** [comment]
When we were making the json format?

**Comment by ssk97** [comment]
I don't think so? We never officially defined the JSON in our documentation. We definitely defined them as separate units in the code representation but I'm not sure if we ever decided on that. It's a lot of duplication otherwise which is a little annoying but not crippling.
