### ISSUE TITLE
Destroy Units

### ISSUE THREAD

**Issue by ssk97** [RonWeber/DataStrategyGame#9]
Need to destroy units when their hp drops below 0.

Possibly also if you move another unit on top of it and/or a specific delete function?

**Comment by RonWeber** [comment]
So far I clean up dead units at end of turn.  We do need to think about specific delete functions.

**Comment by ssk97** [comment]
Changing that so that it happens continuously all the time.
Also making the hp/remaining values into variables inside the data store- this exposes them to LUA and keeps everything consistent.

**Comment by ssk97** [comment]
*By continuously I mean it happens after the UI->update() every timestep and also if anything died while dealing with the previous deaths.
